# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# SEO
# - Update Google indexing after changes to sitemap.xml
# - use FB `Sharing Debugger` to check tags are good, preview of shared link and invalidate previously cached version --> https://developers.facebook.com/tools/debug/
# - use Twitter `Card Validator` to check the Twitter Card Preview --> https://cards-dev.twitter.com/validator
# - use Google `Rich Result` tool --> https://search.google.com/test/rich-results
# - Audit site SEO. for example use - UberSuggest to check site

title: המרד בהכחדה
email: your-email@example.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://xrisrael.earth" # the base hostname & protocol for your site, e.g. http://example.com

# Site SEO Metadata (related to the `Jekyll SEO Tag` Plugin. Instructions: https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
description:
#tagline: תנועת המרד בהכחדה
author: IsraelRebellion
twitter:
  username: IsraelRebellion
  card: summary_large_image
facebook:
  publisher: XRisrael
logo: /assets/logo.svg
social:
  name: Israel Rebellion
  links:
    - https://twitter.com/IsraelRebellion
    - https://www.facebook.com/XRisrael
    - https://www.instagram.com/extinctionrebellionisrael/
    - https://www.instagram.com/redrebelbrigadeisrael/
    - https://rebellion.global/
    - https://extinctionrebellion.uk/
defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/about.webp

#google_site_verification
#webmaster_verifications:
#  google: 1234
#  bing: 1234
#  alexa: 1234
#  yandex: 1234
#  baidu: 1234
lang: il_HE
timezone: Asia/Jerusalem

#
sass:
    sass_dir: _sass

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - lightbox

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/workspace.xml
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
